
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author navee
 */
public class adminForm extends javax.swing.JFrame {

    /** Creates new form adminForm */
    public adminForm() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
        status_txtfield.setEditable(false);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qms", "root", "");
            String sql = "SELECT productService FROM call_quotations";
            PreparedStatement state = conn.prepareStatement(sql);
            ResultSet rs = state.executeQuery();
            product_cmbBox.addItem("--select--");
            while (rs.next()){
                String proSer = rs.getString("productService");
                product_cmbBox.addItem(proSer);
            }  
            product_cmbBox.setSelectedItem("--select--");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    public ArrayList<User> userList(){
        ArrayList<User> usersList = new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qms", "root", "");
            String sql = "SELECT quotations.QID,quotations.companyName,quotations.quantity,quotations.unitPrice,quotations.prevQuotations,quotations.notes from quotations INNER JOIN call_quotations ON quotations.SID=call_quotations.SID WHERE call_quotations.productService=?";
            PreparedStatement state = conn.prepareStatement(sql);
            Object selectedItem = product_cmbBox.getSelectedItem();
            if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                state.setString(1, selectedItemStr);
            }
            ResultSet rs = state.executeQuery();
            User user;
            while(rs.next()){
                user = new User(rs.getInt("QID"), rs.getInt("quantity"), rs.getInt("unitPrice"), rs.getString("companyName"), rs.getString("prevQuotations"), rs.getString("notes"));
                usersList.add(user);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        return usersList;
    }
    
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)quote_tbl.getModel();
        Object[] row = new Object[6];
        model.setRowCount(0);
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getqid();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getqty();
            row[3] = list.get(i).getprice();
            row[4] = list.get(i).getprevq();
            row[5] = list.get(i).getnotes();
            model.addRow(row);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        product_cmbBox = new javax.swing.JComboBox<>();
        close_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        status_txtfield = new javax.swing.JTextField();
        open_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        qty_txtfield = new javax.swing.JTextField();
        setqty_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        quote_tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logout_btn.setText("BACK TO LOGIN");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 140, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("ADD PRODUCT/SERVICE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 45));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("See called quotations");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        product_cmbBox.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        product_cmbBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                product_cmbBoxItemStateChanged(evt);
            }
        });
        product_cmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_cmbBoxActionPerformed(evt);
            }
        });
        getContentPane().add(product_cmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 30));

        close_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        close_btn.setText("CLOSE QUOTATION");
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        status_txtfield.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(status_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, 40));

        open_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        open_btn.setText("RE-OPEN QUOTATION");
        open_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_btnActionPerformed(evt);
            }
        });
        getContentPane().add(open_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 180, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qty");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(qty_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, 40));

        setqty_btn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        setqty_btn.setText("SET QUANTITY");
        setqty_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setqty_btnActionPerformed(evt);
            }
        });
        getContentPane().add(setqty_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 40));

        jScrollPane2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        quote_tbl.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        quote_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QID", "Company Name", "Quantity", "Unit Price", "Any Previous Quotations?", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(quote_tbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 920, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        SelectUser selectuser = new SelectUser();
        selectuser.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addProduct addproduct = new addProduct();
        addproduct.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        try{         
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qms", "root", "");
            String sql = "UPDATE call_quotations SET status='Closed' WHERE productService=?";
            PreparedStatement state = conn.prepareStatement(sql);       
            Object selectedItem = product_cmbBox.getSelectedItem();
            if(selectedItem == "--select--"){
                JOptionPane.showMessageDialog(null,"Please select an item first");
            }
            else if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                state.setString(1, selectedItemStr);
            }
            state.executeUpdate();
            sql = "SELECT status FROM call_quotations WHERE productService=?";
            state = conn.prepareStatement(sql);
            if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                state.setString(1, selectedItemStr);
            }
            ResultSet rs = state.executeQuery();
            while(rs.next()){
                status_txtfield.setText(rs.getString("status"));
            }  
            JOptionPane.showMessageDialog(null,"Status successfully updated");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_close_btnActionPerformed

    private void open_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_btnActionPerformed
        try{         
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qms", "root", "");
            String sql = "UPDATE call_quotations SET status='Open' WHERE productService=?";
            PreparedStatement state = conn.prepareStatement(sql);       
            Object selectedItem = product_cmbBox.getSelectedItem();
            if(selectedItem == "--select--"){
                JOptionPane.showMessageDialog(null,"Please select an item first");
            }
            else if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                state.setString(1, selectedItemStr);
            }
            state.executeUpdate(); 
            sql = "SELECT status FROM call_quotations WHERE productService=?";
            state = conn.prepareStatement(sql);
            if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                state.setString(1, selectedItemStr);
            }
            ResultSet rs = state.executeQuery();
            while(rs.next()){
                status_txtfield.setText(rs.getString("status"));
            }  
            JOptionPane.showMessageDialog(null,"Status successfully updated");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_open_btnActionPerformed

    private void product_cmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_cmbBoxActionPerformed
        
    }//GEN-LAST:event_product_cmbBoxActionPerformed

    private void setqty_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setqty_btnActionPerformed
        try{         
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qms", "root", "");
            String sql = "UPDATE call_quotations SET quantity=? WHERE productService=?";
            PreparedStatement state = conn.prepareStatement(sql);       
            Object selectedItem = product_cmbBox.getSelectedItem();
            if(selectedItem == "--select--"){
                JOptionPane.showMessageDialog(null,"Please select an item first");
            }
            else if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                int qty = Integer.parseInt(qty_txtfield.getText());
                state.setInt(1, qty);
                state.setString(2, selectedItemStr);
            }
            state.executeUpdate();
            JOptionPane.showMessageDialog(null,"Quantity successfully updated");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_setqty_btnActionPerformed

    private void product_cmbBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_product_cmbBoxItemStateChanged
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/qms", "root", "");
            String sql = "SELECT status,quantity FROM call_quotations WHERE productService=?";
            PreparedStatement state = conn.prepareStatement(sql);       
            Object selectedItem = product_cmbBox.getSelectedItem();
            if (selectedItem != null){
                String selectedItemStr = selectedItem.toString();
                state.setString(1, selectedItemStr);
            }
            ResultSet rs = state.executeQuery();
            while(rs.next()){
                status_txtfield.setText(rs.getString("status"));
                qty_txtfield.setText(rs.getString("quantity"));
            } 
            show_user();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_product_cmbBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton open_btn;
    private javax.swing.JComboBox<String> product_cmbBox;
    private javax.swing.JTextField qty_txtfield;
    private javax.swing.JTable quote_tbl;
    private javax.swing.JButton setqty_btn;
    private javax.swing.JTextField status_txtfield;
    // End of variables declaration//GEN-END:variables

}
